import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>YAB News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Welcome to YAB News
        </h2>

        <p className={styles.description}>
          Keep yourself updated with all the latest news sources!!
        </p>

        <div className={styles.grid}>
          <a href="https://yab-top-latest-indian-news.vercel.app/" className={styles.card}>
            <h2>YAB Indian News</h2>
            <p>Keep yourself updated with the Top Indian News!!</p>
          </a>

          <a href="https://yab-british-news.vercel.app/" className={styles.card}>
            <h2>YAB British News</h2>
            <p>Keep yourself updated with the Top British News!!</p>
          </a>

          <a href="https://yab-australian-news.vercel.app/" className={styles.card}>
            <h2>YAB Australian News</h2>
            <p>Keep yourself updated with the Top Australian News!!</p>
          </a>

          <a href="https://yab-american-news.vercel.app/" className={styles.card}>
            <h2>YAB American News</h2>
            <p>Keep yourself updated with the Top American News!!</p>
          </a>

          <a href="https://yab-indian-technology-news.vercel.app/" className={styles.card}>
            <h2>YAB Indian Technology News</h2>
            <p>Keep yourself Advanced with the Top Indian Tech News!!</p>
          </a>

          <a href="https://yab-indian-sports-news.vercel.app/" className={styles.card}>
            <h2>YAB Indian Sports News</h2>
            <p>Keep yourself Updated with the Top Indian Sports News!!</p>
          </a>

          <a href="https://yab-indian-health-news.vercel.app/" className={styles.card}>
            <h2>YAB Indian Health News</h2>
            <p>Keep yourself Safe & Healthy with the Top Indian Health News!!</p>
          </a>

          <a href="https://yab-indian-business-news.vercel.app/" className={styles.card}>
            <h2>YAB Inidan Bussiness News</h2>
            <p>Keep yourself updated with the Top Indian BusinessNews!!</p>
          </a>

          <a href="https://yab-american-business-news.vercel.app/" className={styles.card}>
            <h2>YAB American Bussiness News</h2>
            <p>Keep yourself updated with the Top American Bussiness News!!</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a> Powered by YAB </a>
      </footer>
    </div>
  )
}
